"""relationships created in models

Revision ID: 13893a27f7e5
Revises: 6ce3d74915f9
Create Date: 2024-06-14 09:28:09.600897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13893a27f7e5'
down_revision = '6ce3d74915f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeStamp', sa.String(), nullable=False))
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.DATETIME(), nullable=False))
        batch_op.drop_column('timeStamp')

    # ### end Alembic commands ###
