"""columns added to models, validations added for Physician and Patient models

Revision ID: 6ce3d74915f9
Revises: a84308d6e88a
Create Date: 2024-06-14 08:46:38.685438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce3d74915f9'
down_revision = 'a84308d6e88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('details', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('physician_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_physician_id_physicians'), 'physicians', ['physician_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_patient_id_patients'), 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('physician_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_physician_id_physicians'), 'physicians', ['physician_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_orders_patient_id_patients'), 'patients', ['patient_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('specialty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('office_address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('office_number', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_physicians_office_number'), ['office_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_physicians_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physicians', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_physicians_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_physicians_office_number'), type_='unique')
        batch_op.drop_column('office_number')
        batch_op.drop_column('office_address')
        batch_op.drop_column('specialty')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('username')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('dob')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_patient_id_patients'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_orders_physician_id_physicians'), type_='foreignkey')
        batch_op.drop_column('physician_id')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('date_time')
        batch_op.drop_column('details')
        batch_op.drop_column('complete')
        batch_op.drop_column('order_type')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_patient_id_patients'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_physician_id_physicians'), type_='foreignkey')
        batch_op.drop_column('physician_id')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('details')
        batch_op.drop_column('time')
        batch_op.drop_column('date')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
